; Exchange loactions NUM1 and NUM2 (1 byte positive integers)
;

	ORG	$0000;	START DATA AT 0000
NUM1	FCB	$99;	RESERVE STORAGE FOR THE FIRST NUMBBER
NUM2	FCB	$A0;	RESERVE STORAGE FOR THE SECOND NUMBER
	ORG	$E000;	CONTINUE WITH PROGRAM AT E000
	LDAA	NUM1;	LOAD THE FIRST NUMBER
	LDAB	NUM2;	LOAD THE SECOND NUMBER
	STAA	NUM2;	STORE THE FIRST NUMBER
	STAB	NUM1;	STORE SECOND NUMBER
	NOP;		PROGRAM ENDS